### ISSUE TITLE
Missing analysis.py File in gcog.models Import in trainer.py

### ISSUE THREAD

**Issue by guangfuhao** [IBM/gcog#1]
In gcog/models/trainer.py, there is a line import gcog.models.analysis as analysis, but there is no gcog/models/analysis.py file in the project directory.

**Comment by ito-takuya** [comment]
File was added in commit [58feeba](https://github.com/IBM/gcog/commit/58feeba8fa1faf28ffced73f037f2cb2c09715d6)
